os:
  - linux
dist: trusty
language: c
install:
  - export CHOOSENIM_CHOOSE_VERSION="0.20.0"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
before_script:
  # Add the 'bin' folder to PATH
  - export PATH=$HOME/.nimble/bin:$PATH
script:
  - nimble test
  - nim doc --docSeeSrcUrl:https://github.com/soasme/nim-makrdown/blob/master --project src/markdown.nim
